[book]
authors = ["Eric Huss"]
language = "en"
multilingual = false
title = "The Rust Language"

[output.html]
additional-css = ["css/custom.css"]
curly-quotes = true

[preprocessor.spec]
command = "cargo run --locked --manifest-path=spec/Cargo.toml"

[build]
extra-watch-dirs = ["spec/src", "css"]
